import { Inter,Roboto } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })
export const metadata = {
  title: 'Food App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      
<body className={roboto.className}>
        <main className="max-w-6xl mx-auto p-2 text-gray-700 font-semibold">
         
            {children}
           
        </main>
      </body>
      
      
    </html>
  )
}
